# Site settings
title: 현모링의 블로그 Hyunmoring's Blog
url: "http://hyunmo-oh.github.io"    # the protocol and hostname of your site, eg. `http://laobubu.github.io`
baseurl: "/" # the prefix of your site uri, eg. `/jekyll-theme-EasyBook` or just one slash `/`
timezone: Asia/Seoul
description: >
  description

# Your information
email: hyunmo917@gmail.com
author: 현모링
# avatar: "//www.gravatar.com/avatar/your_email_md5?d=mm&s=135"
avatar: "https://github.com/Hyunmo-OH/Hyunmo-OH.github.io/blob/master/media/jake-the-dog.png"
profile: <br> 빅데이터 과학 연계 전공 과정 학생의 강의 정리용 블로그 입니다!
#twitter_username: twitter_username
github_username:  Hyunmo-OH

# Comment Service (Disqus or 多说)
#  choose one and un-comment the line to active it
disqus_shortname: hyunmo917   # get one: https://disqus.com/admin/signup/
#duoshuo_shortname: xxx  # get one: http://duoshuo.com/create-site/

# Google Analytics
google_analytics_id: UA-128992107-1

permalink: /archivers/:title
gems:
 - jekyll-paginate
 - jekyll-gist
 - jemoji
 - jekyll-sitemap

# Build settings
paginate: 5
paginate_path: "page:num"

highlighter: rouge
markdown: kramdown

kramdown:
  input: GFM
  syntax_highlighter: rouge

theme: jekyll-theme-time-machine
